# Generated by Django 4.2.3 on 2023-08-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_documents_user_alter_education_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
